on: [push]

jobs:
  hello_world_job:
    runs-on: self-hosted
    name: A job to say hello
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2.1.0
    - name: Build and tag Docker Image
      run: |
        docker build .