name: main-workflow

env:
  DOCKER_CONTENT_TRUST: 1
  DOCKER_CONTENT_TRUST_SERVER: "${{ secrets.DOCKER_CONTENT_TRUST_SERVER }}"
  NOTARY_SIGNER_DELEGATION: "${{ secrets.NOTARY_SIGNER_DELEGATION }}"
  IMAGE_REPOSITORY: 263799606133.dkr.ecr.us-east-1.amazonaws.com/notary/signtest2
  IMAGE_TAG: latest
  DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: "${{ secrets.DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE }}"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  sign-image:
    runs-on: self-hosted
    steps:
      - name: check out source code
        uses: actions/checkout@v2

      - name: sign image
        run: ./sign_image.sh
