name: main-workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # run all unit tests
  run-tests:
    runs-on: self-hosted
    steps:
      - name: Check out source code
        uses: actions/checkout@v2