name: main-workflow

env:
  DOCKER_CONTENT_TRUST: 1
  DOCKER_CONTENT_TRUST_SERVER: "${{ secrets.DOCKER_CONTENT_TRUST_SERVER }}"
  NOTARY_SIGNER_DELEGATION: "${{ secrets.NOTARY_SIGNER_DELEGATION }}"
  DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: "${{ secrets.DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE }}"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # build
  sign-image:
    runs-on: self-hosted
    steps:
      # check out source code
      - name: check out source code
        uses: actions/checkout@v2

      # sign image
      - name: test docker trust
        run: ./sign_image.sh
